### ISSUE TITLE
Add Checkout Workflow from Carrier Page

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#183]
**Note: Use of the word "user" here is referring to authenticated users with an Admin or Volunteer role only.**

### Carrier Detail Page
- [x] Add a `Checkout` button to `/carrier` page for authenticated Admin and Volunteer users. 
- If the status of the carrier is Available, the `Checkout` button should show the text `Checkout` and have styling indicating it's clickable.
- If the status of the carrier is Unavailable, the `Checkout` button should show the text `Unavailable` and the styling should indicate not clickable (darker, grayed out, etc). 
- [x] `Checkout` button should bring user to a pop-up view for selecting the member checking the carrier out. This action should take the `POST` method.

### Checkout Popup View
- [ ] The Checkout Popup View should show a list of users - this list should populate all active (see #153 and #157 ) users (all roles included - `admin`, `volunteer` and `member`)
- [ ] The list of active members should populate as links to a new Checkout Page

### Checkout Page
- On clicking a user link in the Checkout Popup View, the user should navigate to a view that lists the following:
- [x] The specific carrier being checked out
- [ ] The `user` profile information to verify that the information is accurate
- [ ] A display showing that users `agreements` have been signed or not (there are a few types of `agreements`, maybe a green check to the ones that have been signed and a red X for those that haven't)
- [ ] The user's `membership type`
- [x] A final "Checkout" button to complete the transaction.

### Process Transaction
- [ ] On clicking the final "Checkout" button, a `POST` request should be sent with the member and volunteer information to track checkout transactions.
- [ ] A successful `POST` should create a `Loan` object with the `member`, `volunteer` (or `admin`), `carrier` info
- [ ] After successful `POST`, display a flash message verifying success. 

### Carrier Detail Page
![New Wireframe 1 (1)](https://user-images.githubusercontent.com/47750744/67577123-e3344580-f70d-11e9-9a50-72f9cd590fa2.png)

### Clicking "Checkout" from Carrier Detail Page
![New Wireframe 2 (3)](https://user-images.githubusercontent.com/47750744/67577132-e5969f80-f70d-11e9-9252-3b3cdcd79961.png)

### TODO
- [ ] Some concerns about UX and overall flow that will need to be flushed out later.
- [ ] In the Checkout Page, we should display existing `Loan` objects assigned to that user and prevent checking out more carriers than the membership type allows

**Comment by pollygee** [comment]
@dixpac is this issue covered by the functionality you just added?

**Comment by dixpac** [comment]
@pollygee not everything

**Covered:**
- Checkout button is visible to `admin or volunteer`
- When clicking checkout modal is shown where user can choose member and due date
- Clicking `Checkout` button on the modal saves new Loan object

**Not-covered**

- Show disable checkout if carrier status is unavailable
- Agreements stuff
- Better search/autocomplete on the members dropdown
- Nicer looking data select if necessary


I would also love to move modal to full page, just so we have more working space, wdyt?

----------------------------

I will send few more PRs to fix leftover stuff, @abronkema  can you pull latest and see how checkout works atm, and add necessary stuff that needs to be done which I've missed

**Comment by pollygee** [comment]
OK great thanks so much!  I'm going to assign you to this then just for clarity.

**Comment by mark100net** [comment]
MOST of checkin/checkout is done now but there is nothing done about agreements in relation to this.  The other exception is "editing" a loan (i.e. other than indicating the carrier is returned....things like adding notes) but that is straightforward.

I would suggest we get a review of what we have now and get an idea of the specifics of what we still need.

**Comment by pollygee** [comment]
I'm going to close this issue.  Most of the issues here have been addressed.  I think we need new specific issues for the changes we need from where we stand now.
